name: with_me_app
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.15.0-268.18.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^1.0.3
  url_launcher: ^6.1.2
  google_fonts: ^3.0.1
  device_preview: ^1.1.0
  flutter_screenutil: ^5.5.3+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/top_page_image/
    - assets/images/A/
    - assets/images/B/
    - assets/images/C/
    - assets/images/D/
    - assets/images/E/
    - assets/images/F/
    - assets/images/G/
    - assets/images/H/
    - assets/images/I/
